describe ("automationexercise test cases", ()=> {
    it ("Register Use", ()=>{

       /* cy.visit ('https://automationteststore.com')
        cy.get('#customer_menu_top > li > a').click()
        cy.get('#accountFrm > fieldset > .btn').click()
        cy.get('#AccountFrm_firstname').type("mariami")
        cy.get('#AccountFrm_lastname').type("mesablishvili")
        cy.get('#AccountFrm_newsletter1').click()
        cy.get('.col-md-2 > .btn').click()
        cy.get('.alert').should("be.visible")

        cy.visit ('https://automationteststore.com')
        cy.get('#customer_menu_top > li > a').click()
        cy.get('#accountFrm > fieldset > .btn').click()
        cy.get('#AccountFrm_firstname').type("mariami")
        cy.get('#AccountFrm_lastname').type("mesablishvili")
        cy.get('#AccountFrm_email').type("mesabli10@gmail.com")
        cy.get('#AccountFrm_telephone').type("558201041")
        cy.get('#AccountFrm_company').type("tbc")
        cy.get('#AccountFrm_address_1').type("ashby street")
        cy.get('#AccountFrm_city').type("norwich")
        cy.get('#AccountFrm_zone_id').select("Norfolk")
        cy.get('#AccountFrm_postcode').type("nr13pu")
        cy.get ("#AccountFrm_loginname").type("marimer")
        cy.get('#AccountFrm_password').type("mari123")
        cy.get('#AccountFrm_confirm').type("mari123")
        cy.get('#AccountFrm_agree').click()
        cy.get('#AccountFrm_newsletter1').click()
        cy.get('.col-md-2 > .btn').click()
        cy.get('.mb40 > .btn').click()
        cy.get('.maintext').should("be.visible")
        cy.get('#customer_menu_top > :nth-child(1) > .top > .menu_text').should("have.text","Welcome back mariami")
     */
    
         cy.visit ('https://automationteststore.com')
         cy.get('#topnav > .form-control').select("Specials")
         cy.get('.maintext').should("be.visible")
         cy.url("https://automationteststore.com/index.php?rt=product/special").should('include', 'product/special') 
 })
})